#  app config file will contain any variable settings.

defaults: &defaults
    system_ip: localhost
    interface: en0
    ip_filter: udp and port 53

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  
  
