# SQLite version 3.x
#   gem install sqlite3
default: &default
  adapter: sqlite3

development:
  <<: *default
  database: db/packet_cache_development.sqllite3

test:
  <<: *default
  database: db/packet_cache_test.sqllite3

production:
  <<: *default
  database: db/packet_cache_production.sqllite3

remote_default: &remote_default
  adapter: mysql2
  database: jamnent_game_engine_production
  username: root
  password: vfT43I3T
  host: 127.0.0.1
  port: 3307

cloud_development:
  <<: *remote_default
  #username: root
  #host: localhost
  #password: roadster
  #database: jamnent_game_engine_production
  
cloud_test:
  <<: *remote_default

cloud_production:
  <<: *remote_default

